import { st } from "./shared/analysisStyles";

export default function OverviewWorkspace() {
  const stockAlerts = [
    { product: "Roundup", issue: "Expiry Risk", detail: "Expires in 18 days", status: "warning" },
    { product: "Mospilan", issue: "Low Stock", detail: "Only 8 bottles left", status: "danger" },
  ];

  const recentActivity = [
    { text: "Invoice INV-1042 generated by admin.", time: "10 mins ago" },
    { text: "New stock batch added for Roundup.", time: "2 hours ago" },
    { text: "Supplier payment recorded for Bayer.", time: "4 hours ago" },
  ];

  return (
    <>
      <div style={st.card}>
        <div style={st.cardTop}>
          <div>
            <h2 style={st.cardTitle}>Critical Alerts</h2>
            <p style={st.cardSubtext}>Immediate operational issues requiring awareness.</p>
          </div>
        </div>

        <div style={st.tableWrap}>
          <div style={st.tableHead}>
            <span style={{ flex: 2 }}>Product</span>
            <span style={{ flex: 1.2 }}>Issue</span>
            <span style={{ flex: 2 }}>Details</span>
            <span style={{ width: 90 }}>Status</span>
          </div>

          {stockAlerts.map((item, index) => (
            <div key={index} style={st.tableRow}>
              <span style={{ flex: 2, ...st.cellBold }}>{item.product}</span>
              <span style={{ flex: 1.2 }}>{item.issue}</span>
              <span style={{ flex: 2 }}>{item.detail}</span>
              <div style={{ width: 90 }}>
                <div style={{
                  ...st.badge,
                  ...(item.status === "warning" ? st.badgeWarning : item.status === "danger" ? st.badgeDanger : st.badgeNeutral)
                }}>
                  {item.status}
                </div>
              </div>
            </div>
          ))}
          {stockAlerts.length === 0 && <div style={st.emptyState}>No critical alerts at this time.</div>}
        </div>
      </div>

      <div style={st.card}>
        <div style={st.cardTop}>
          <div>
            <h2 style={st.cardTitle}>Recent Activity</h2>
            <p style={st.cardSubtext}>Latest operational events across the system.</p>
          </div>
        </div>
        
        <div style={st.tableWrap}>
          {recentActivity.map((item, index) => (
             <div key={index} style={st.tableRow}>
               <span style={{ flex: 1 }}>{item.text}</span>
               <span style={{ width: 100, ...st.cellMuted, textAlign: "right" }}>{item.time}</span>
             </div>
          ))}
        </div>
      </div>
    </>
  );
}
